Traceback (most recent call last):
  File "01nested_exception.py", line 11, in <module>
    f()
  File "01nested_exception.py", line 5, in f
    raise Exception("oops")
Exception: oops
